version: '3.7'

services:

  workspace:
    build:
      context: ./docker/workspace
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - USERNAME=${REMOTE_USER}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    env_file: ../.env
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "3306:3306"
      - "8080:8080"
      - "8081:8081"
    init: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ../:../
    working_dir: ../
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

  nginx:
    build: ./docker/nginx
    env_file: ../.env
    volumes:
      - ./docker/nginx/config:/etc/nginx/conf.d/
      - ../.docker/data/nginx/log:/var/log/nginx
      - ../:/var/www
    depends_on:
      - php
    network_mode: service:workspace

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - USERNAME=${REMOTE_USER}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - XDEBUG_REMOTE_CONNECT_BACK=${XDEBUG_REMOTE_CONNECT_BACK}
        - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
    env_file: ../.env
    volumes:
      - ../:../
    working_dir: ./
    network_mode: service:workspace

  composer:
    restart: 'no'
    image: composer/composer
    command: install
    env_file: ../.env
    volumes:
      - ../:./
    working_dir: ./

  mariadb:
    image: mariadb:10.5
    env_file: ../.env
    volumes:
      - mariadb:/var/lib/mysql
      - ../.docker/data/mysql/log:/var/log/mysql
      - ./docker/mariadb/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      default:
        aliases:
          - mysql
          
  redis:
    image: redis:6.0
    env_file: ../.env
    volumes:
      - redis:/tmp/

volumes:
  mariadb:
    driver: local
  redis:
    driver: local
